sonar.projectKey=EntreAulas_Front
sonar.projectName=EntreAulas_Front
sonar.host.url=http://sonarqube:9000
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.ts,src/test/**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/build/**,src/test/**

# Vitest genera este archivo con npm run test:coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/test/**,**/*.test.ts,**/*.test.tsx,**/*.d.ts,src/main.tsx
